name: Ansible

on:
  push:
  workflow_dispatch:

jobs:
  run-ansible-play:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Inventory File
        run: |
          cat <<EOF > inventory.ini
          [ec2]
          myec2 ansible_host=${{ env.EC2_IP }} ansible_user=${{ env.EC2_USER }} ansible_ssh_private_key_file=~/.ssh/id_rsa
          EOF

      - name: Run Ansible Task
        run: |
          ansible-playbook AWS_configuration/ec2.yml -i inventory.ini
