name: Control_Workflow
on:
    workflow_dispatch:
        inputs:
            env:
                description: "Select the env"
                required: true
                type: choice
                default: dev
                options:
                    - "dev"
                    - "test"
                
    
jobs:
    Deploy_Dev:
        runs-on: ubuntu-latest
        if: github.event.inputs.env == 'dev'
        steps:
            - name: Echo
              run: echo "dev"

    Deploy_Test:
        if: github.event.inputs.env == 'test'
        runs-on: ubuntu-latest
        steps:
            - name: Test
              run: echo "test"
