name: Control_Workflow
on:
    
    workflow_dispatch:
        inputs:
            env:
                description: "Select the env"
                required: true
                type: choice
                default: dev
                options:
                    - "dev"
                    - "test"
                
    
jobs:
    Build_Dev:
        runs-on: ubuntu-latest
        if: github.event.inputs.env == 'dev'
        steps:
            - name: Echo dev
              run: echo "build dev"
    Deploy_Dev:
        runs-on: ubuntu-latest
        needs: [Build_Dev]
        if: github.event.inputs.env == 'dev'
        steps:
            - name: Echo
              run: echo "dev"
    
    Build_Test:
        if: github.event.inputs.env == 'test'
        runs-on: ubuntu-latest
        steps:
            - name: Test
              run: echo "test"

    Deploy_Test:
        needs: [Build_Test]
        if: github.event.inputs.env == 'test'
        runs-on: ubuntu-latest
        steps:
            - name: Test
              run: echo "test"

    Manual_Approval:
        runs-on: ubuntu-latest
        needs: [Deploy_Test]
        if: github.event.inputs.env == 'test'
        steps:
        - name: Manual Approval
          id: approval
          uses: actions/github-script@v5
          with:
            script: |
                const response = await github.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                event: 'APPROVE',
                });
                console.log(response.data);