name: Control_Workflow
on:
    
    workflow_dispatch:
        inputs:
            env:
                description: "Select the env"
                required: true
                type: choice
                default: dev
                options:
                    - "dev"
                    - "test"
                
    
jobs:
    Build_Dev:
        runs-on: ubuntu-latest
        if: github.event.inputs.env == 'dev'
        steps:
            - name: Echo dev
              run: echo "build dev"
    Deploy_Dev:
        runs-on: ubuntu-latest
        needs: [Build_Dev]
        if: github.event.inputs.env == 'dev'
        steps:
            - name: Echo
              run: echo "dev"
    
    Build_Test:
        if: github.event.inputs.env == 'test'
        runs-on: ubuntu-latest
        steps:
            - name: Test
              run: echo "test"

    Deploy_Test:
        needs: [Build_Test]
        if: github.event.inputs.env == 'test'
        runs-on: ubuntu-latest
        steps:
            - name: Test
              run: echo "test"

    Manual_Approval:
        runs-on: ubuntu-latest
        needs: [Deploy_Test]
        if: github.event.inputs.env == 'test'
        steps:
        - uses: trstringer/manual-approval@v1
          with:
                secret: ${{ github.TOKEN }}
                approvers: mdmoqaddas,
                minimum-approvals: 1
                issue-title: "Deploying v1.3.5 to prod from staging"
                issue-body: "Please approve or deny the deployment of version v1.3.5."
                exclude-workflow-initiator-as-approver: false
                additional-approved-words: ''
                additional-denied-words: ''