name: Control_Workflow
on:
    
    workflow_dispatch:
        inputs:
            env:
                description: "Select the env"
                required: true
                type: choice
                default: dev
                options:
                    - "dev"
                    - "test"
                
    
jobs:
    Build_Dev:
        runs-on: ubuntu-latest
        if: github.event.inputs.env == 'dev'
        steps:
            - name: Echo dev
              run: echo "build dev"
    Deploy_Dev:
        runs-on: ubuntu-latest
        needs: [Build_Dev]
        if: github.event.inputs.env == 'dev'
        steps:
            - name: Echo
              run: echo "dev"
    
    Build_Test:
        if: github.event.inputs.env == 'test'
        runs-on: ubuntu-latest
        steps:
            - name: Test
              run: echo "test"

    Deploy_Test:
        needs: [Build_Test]
        if: github.event.inputs.env == 'test'
        runs-on: ubuntu-latest
        steps:
            - name: Test
              run: echo "test"
    Approval:
        needs: [Deploy_Test]
        runs-on: ubuntu-latest
        if: github.event.inputs.env == 'test'
        steps:
            - name: Awaiting approval
              run: echo "Awaiting manual approval"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Approval step
              uses: hmarr/auto-approve-action@v2.0.0
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}

    Post_Approval_Job1:
        runs-on: ubuntu-latest
        needs: [Approval]
        if: github.event.inputs.env == 'test'
        steps:
            - name: Echo after approval
              run: echo "Post approval job 1"