name: EKS
on:
    push:
    workflow_dispatch:

jobs:
    eks_create:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout Code"
              uses: actions/checkout@v4
            - name: "Setup Terraform"
              uses: hashicorp/setup-terraform@v3
            - name: "Configure AWS Credentials"
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
                aws-region: ap-south-1
            - name: "Initializing the terrafrom"
              run: terraform init 
              working-directory: eks