name: EKS
on:
    push:
    workflow_dispatch:
        inputs:
            destroy:
                description: "Destroy the resource"
                required: true
                type: boolean

jobs:
    eks_create:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout Code"
              uses: actions/checkout@v4
            - name: "Setup Terraform"
              uses: hashicorp/setup-terraform@v3
            - name: "Configure AWS Credentials"
              uses: aws-actions/configure-aws-credentials@v3
              with:
                aws-access-key-id: ${{ secrets.ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
                aws-region: ap-south-1
            - name: "Initializing the terrafrom"
              run: terraform init 
              working-directory: eks
            - name: "Terrafrom plan"
              run: terraform plan
              working-directory: eks
            - name: "Applying Terraform"
              run: terraform apply --auto-approve
              working-directory: eks

    eks_destroy:
        runs-on: ubuntu-latest
        needs: eks_create
        if: github.actions.inputs.destroy == 'true'
        steps:
            - name: "Checkout Code"
              uses: actions/checkout@v4
            - name: "Setup Terraform"
              uses: hashicorp/setup-terraform@v3
            - name: "Configure AWS Credentials"
              uses: aws-actions/configure-aws-credentials@v3
              with:
                aws-access-key-id: ${{ secrets.ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
                aws-region: ap-south-1
            - name: "Destroying the resource"
              run: terraform destroy --auto-approve
              working-directory: eks